name: Build and Publish Add-on

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: get_version
        run: echo "version=$(jq -r .version ./warema_bridge/config.json)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./warema_bridge
          platforms: linux/amd64,linux/aarch64,linux/armv7,linux/armhf
          push: true
          no-cache: true
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/amd64-base:3.19
          tags: |
            ghcr.io/aschmidt11wangen/addon-warema-bridge:latest
            ghcr.io/aschmidt11wangen/addon-warema-bridge:${{ steps.get_version.outputs.version }}
